theme = "lynx"
title = "Terps for Bike Lanes"

enableEmoji = true
disableKinds = ["taxonomy", "term"]

[author]
  name = "Terps for Bike Lanes"
  headline = "Let's get micromobility infrastructure at UMD!"
  image = "author.png"
  links = [
    { link = { href = "https://blog.umd.edu/terps4bikelanes", text = "Our new website" } },
  ]

[markup.highlight]
  noClasses = false

[markup.goldmark]
[markup.goldmark.renderer]
  unsafe = true
