theme = "lynx"
title = "Terps for Bike Lanes"

enableEmoji = true
disableKinds = ["taxonomy", "term"]

[author]
  name = "Terps for Bike Lanes"
  headline = "Let's get micromobility infrastructure at UMD!"
  image = "author.png"
  links = [
    { link = { href = "https://forms.gle/tTmrW5XeTnKpTpbS6", text = "Sign our petition" } },
    { link = { href = "letter/", text = "Letter to Pines", target = "_self" } },
    { email = { href = "mailto:terps4bikelanes@gmail.com", text = "Contact us" } },
    { link = {  href = "https://terplink.umd.edu/organization/terps4bikelanes", text = "TerpLink" } },
    { instagram = "https://www.instagram.com/terps4bikelanes" },
    { slack = "https://join.slack.com/t/terps4bikelanes/signup" },
    { link = {href = "https://app.markup.io/markup/05cb82e2-b693-4fc2-b9d5-3eac5959b297", text = "Report accidents/close calls"} },
    { link = {href = "https://app.markup.io/markup/e6842b98-96b0-4bb4-bcd9-1357b911c042", text = "Report poor infrastructure"} },
  ]

[markup.highlight]
  noClasses = false

[markup.goldmark]
[markup.goldmark.renderer]
  unsafe = true
